// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLDkAwbPr_ptKYM342jgaaGC2QEHrFTk',
    appId: '1:815722667265:web:408ea353c63f4f12a20f00',
    messagingSenderId: '815722667265',
    projectId: 'newsapp-de375',
    authDomain: 'newsapp-de375.firebaseapp.com',
    storageBucket: 'newsapp-de375.appspot.com',
    measurementId: 'G-4MSVZF44BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuMPshGEHbH9UV_UIed4hZe_H8g3uF3I',
    appId: '1:815722667265:android:83d08a87f0ff82fca20f00',
    messagingSenderId: '815722667265',
    projectId: 'newsapp-de375',
    storageBucket: 'newsapp-de375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLqW3fMu_l4Fbi30NR7Ms1AZNtvvkxXI',
    appId: '1:815722667265:ios:e4cd07e46b793321a20f00',
    messagingSenderId: '815722667265',
    projectId: 'newsapp-de375',
    storageBucket: 'newsapp-de375.appspot.com',
    androidClientId: '815722667265-5pl176h7ms50qi7hplqh8gdfvprnqgjs.apps.googleusercontent.com',
    iosClientId: '815722667265-icb137vggdfpt746j6h3sp49m6o14cf7.apps.googleusercontent.com',
    iosBundleId: 'com.inzziyon.newsShort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrLqW3fMu_l4Fbi30NR7Ms1AZNtvvkxXI',
    appId: '1:815722667265:ios:7dc5381d337f7ce2a20f00',
    messagingSenderId: '815722667265',
    projectId: 'newsapp-de375',
    storageBucket: 'newsapp-de375.appspot.com',
    androidClientId: '815722667265-5pl176h7ms50qi7hplqh8gdfvprnqgjs.apps.googleusercontent.com',
    iosClientId: '815722667265-tt5egari9lu1bl6pk38ilkvlu19tvaf8.apps.googleusercontent.com',
    iosBundleId: 'com.inzziyon.newsShort.RunnerTests',
  );
}
